### PR TITLE
AWS Lambda

### PR DESCRIPTION
**Pull request by cristoformihai**
I have a Salus IT 500 interface and you work it's a real help form me.
However, I need some help hosting this on AWS Lambda.
I created a new skill, I have modified the js file according to this code, but the skill it's not working.
I suspect it's because it has dependencies. The Lambda service however does not allow me to upload any file so I am not able to upload all the necessary libraries.
I there any other way to do this?
Thank you!

### CODE REVIEW

**Comment by matthewturner** [comment]
@cristoformihai have you tried running the package.sh script and uploading the package.zip file it creates? This should contain all the node_modules you need.

**Comment by cristoformihai** [comment]
Hi,
Thank you for your reply.Running the package only adds two files to the zip: index.js and package.json but none of the dependencies. 
Also, I have noticed a small problem on my salus.The line if (body == '"online"') callback();

should be changed with if ((body == '"online"') || (body == '"online lowBat"')) callback();

It seems my device is low battery but it's still working.
Thank you,Mihai

    On Tuesday, March 20, 2018, 5:59:41 PM GMT+2, Matt Turner <notifications@github.com> wrote:  
 
 
@cristoformihai have you tried running the package.sh script and uploading the package.zip file it creates? This should contain all the node_modules you need.

**Comment by matthewturner** [comment]
Ah, sorry, you will need to run `npm install` beforehand. I'll add this as a step to the `package.sh` script. 

Good catch on the status! I'm still working on the hold time (not fully working yet) and I'll raise a PR for both things.

**Comment by cristoformihai** [comment]
Anyway, I have managed to host the service on my NAS and I have connected it to Amazon Web services.However, I still have two problems and maybe you have an idea what can I do:
1. Using putty, I start the service with the following command: USERNAME=.... PASSWORD=... node server &    However, as soon as I close putty the service stops.
2. When testing the service using the Amazon test interface everything works fine. However. when talking to Alexa directly, she only understands "Open boiler" and responds  "Boiler is online".    If I say "Alexa, ask boiler the temperature" for example, she just shuts down as soon as she processes the question and gives no response.
 
Thank you!

Regards,Mihai

    On Wednesday, March 21, 2018, 12:05:44 PM GMT+2, Matt Turner <notifications@github.com> wrote:  
 
 
Ah, sorry, you will need to run npm install beforehand. I'll add this as a step to the package.sh script.

Good catch on the status! I'm still working on the hold time (not fully working yet) and I'll raise a PR for both things.

**Comment by matthewturner** [comment]
Hi Mihai,

Sorry, I've not tried running it locally. Are you running an alexa-app-server as detailed [here](https://github.com/alexa-js/alexa-app-server)?

I'm not familiar with your NAS box so I don't know how running background tasks works. I'm running mine successfully on a lambda function with almost zero cost.

I've now got the (optional) hold time working and will raise a PR shortly.

Regards,
Matt

**Comment by bluemonki** [comment]
@cristoformihai you need to use something like "nohup" (https://www.computerhope.com/unix/unohup.htm)  in order to keep the process running once you've logged out of putty

**Pull request merged**
